python main.py \
    --root_dir ./flickr30k/flickr30k_images \
    --annotations_file ./flickr30k/results.csv \
    --epochs 100 \
    --batch_size 4 \
    --learning_rate 5e-5 \
    --logging_steps 10 \
    --save_epochs 1 \
    --save_steps 500 \
    --output_dir ./results \
    --log_dir ./loss_logging \
    --checkpoint_dir ./checkpoint_dir
